### ISSUE TITLE
Mock

### ISSUE THREAD

**Issue by cs-adann-simoes** [cs-leonel-lima/magic-the-gathering#7]
Podemos fazer um mock de dados nas model classes? 
A ideia é usar um método estático da classe para buscar esse mock.

**Comment by cs-joao-souza** [comment]
@cs-adann-simoes então, fiz o primeiro CodeReview seus aqui e isso foi um dos pontos. Acredito que futuramente vocês irão acessar uma API, então por enquanto, pode deixar lá até mesmo por causa de acesso aos bundles mas depois vocês irão utilizar apenas nos testes. O legal é que para esse problema vocês podem pensar em um método mais genérico para fazer os mocks ou carregar os mocks. Acha a ideia boa?
